version: '3.8'
services:
  zookeeper-services:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: zookeeper-container
    restart: unless-stopped
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks: 
      - kafka_network
  kafka-services:
    image: docker.io/bitnami/kafka:3.4
    container_name: kafka-container
    restart: unless-stopped
    ports:   
        - "19092:19092"
        - "29092:29092"  
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-services:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CONTROLLER://:19092,EXTERNAL_SAME_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CONTROLLER://kafka-services:19092,EXTERNAL_SAME_HOST://localhost:29092 
      - KAFKA_KRAFT_CLUSTER_ID=1
      - KAFKA_CLUSTER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper-services
    networks: 
      - kafka_network

networks:
  kafka_network:
    name: kafka_same_host_net

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
